services:
  - type: web
    name: grammar-web-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    build:
      runtime: "python-3.10.13"
